spring.application.name=depenses_personnelles

# 1. URL de la base de données (remplace "nom_de_ta_base" par le nom réel de ta base MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/t_mes_depenses?useSSL=false&serverTimezone=UTC

# 2. Identifiants de connexion à MySQL (par défaut sur une installation locale)
spring.datasource.username=root
spring.datasource.password=1234

# 3. Le pilote de connexion
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. La magie d'Hibernate : création automatique des tables
# premier lencement ""create"" puis modifier a ""update""
spring.jpa.hibernate.ddl-auto=update

# 5. Afficher les requêtes SQL générées dans la console d'IntelliJ (très utile pour apprendre !)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true